In [1]:
from rag_engine import RAGEngine

c:\Users\91790\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

WARNING:tensorflow:From c:\Users\91790\anaconda3\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [2]:
engine = RAGEngine()

Let's verify

In [3]:
engine.embedder

SentenceTransformer(
  (0): Transformer({'max_seq_length': 256, 'do_lower_case': False}) with Transformer model: BertModel
  (1): Pooling({'word_embedding_dimension': 384, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
  (2): Normalize()
)

In [4]:
engine.pc

In [5]:
engine.index

In [6]:
engine.groq_client

ok

In [7]:
context = engine.query_vector_db("what is total revenue in january 2017", 2)

In [8]:
context

'In 2017, the total revenue for the month of January was 529883.00 USD. This reflects the booking revenue generated by the hotel during this period. 0.731459558 In 2016, the total revenue for the month of January was 259290.00 USD. This reflects the booking revenue generated by the hotel during this period. 0.723765314'

In [9]:
query = "what is total revenue in january 2017"

In [10]:
res = engine.generate_response(
    query, 
    context
)

In [11]:
res

'The total revenue in January 2017 is 529883.00 USD.'